### ISSUE TITLE
[Bug/Improvement] Brightness scroll has wierd text

### ISSUE THREAD

**Issue by kylianpl** [Adventurecraft-Awakening/AC-Legacy-Mod#31] opened 2023-06-04 12:51 UTC
In vanilla, the brightness goes from Moody to Bright, but with the optifine menu, it goes from OFF to 100%

AC:
![Screenshot_20230604_144924](https://github.com/Adventurecraft-Awakening/AC-Legacy-Mod/assets/66625058/17fa2a27-297e-45d6-a9a7-1c2b2dbd0f3a)
![Screenshot_20230604_145028](https://github.com/Adventurecraft-Awakening/AC-Legacy-Mod/assets/66625058/4c6a01c0-ea5a-466c-8f6c-4a6a73dac881)
![Screenshot_20230604_144949](https://github.com/Adventurecraft-Awakening/AC-Legacy-Mod/assets/66625058/5ddb6ccd-f4ab-4532-8c33-bc337a9134ef)

Vanilla:
![Screenshot_20230604_145103](https://github.com/Adventurecraft-Awakening/AC-Legacy-Mod/assets/66625058/5a973f10-1fd8-42fa-9bcc-4e7925fe2799)
![Screenshot_20230604_145126](https://github.com/Adventurecraft-Awakening/AC-Legacy-Mod/assets/66625058/ac676ac6-ef12-4b09-8221-69f8f20afc2e)
![Screenshot_20230604_145137](https://github.com/Adventurecraft-Awakening/AC-Legacy-Mod/assets/66625058/30b99f67-1269-4d93-ab21-bf1ea5631ab9)

**Comment by RyuuSlayer** [comment] 2023-06-14 14:36
Yeah, Optifine, intended behaviour. Closing the issue.

**Comment by RyuuSlayer** [comment] 2023-06-14 14:36
Yeah, Optifine, intended behaviour. Closing the issue.

**Closed** 2023-06-14 14:36 UTC
Labels: enhancement
